language: node_js
node_js:
  - "20.19.4"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - npm install -g codecov
  - yarn install
script:
  - yarn --version
  - yarn --check-cache
  - yarn lint
  - yarn test
  - yarn test:coverage
  - codecov
