capacity = "2"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
#idam_api_url = "https://idam-api.aat.platform.hmcts.net"
asp_name = "ccd-case-activity-api-aat"
asp_rg = "ccd-case-activity-api-aat"
use_shared_appinsight = "true"
