idam_api_url = "https://idam-api.platform.hmcts.net"
cors_origin = "https://www.ccd.platform.hmcts.net,https://ccd.platform.hmcts.net"
capacity = "2"
asp_name = "ccd-case-activity-api-prod"
asp_rg = "ccd-case-activity-api-prod"
